# Generated by Django 6.0.4 on 2026-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
