# Generated by Django 6.0.4 on 2026-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0003_alter_talaba_options_remove_talaba_familiya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='capacity',
            field=models.IntegerField(blank=True, default=None, help_text="0 yoki bo'sh — cheklov yo'q", null=True),
        ),
    ]
