# Generated by Django 6.0.4 on 2026-04-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boshlangan_sana', models.DateField()),
                ('muddat', models.IntegerField(help_text='Kurs muddati kunlarda')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=15)),
                ('tugilgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royxatdan_otish_sanasi', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan'), ('bekor_qilingan', 'Bekor qilingan')], default='faol', max_length=20)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurslar.kurs')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurslar.talaba')),
            ],
        ),
    ]
